Switch to Docker actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,52 +17,59 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       -
+        name: Checkout
+        uses: actions/checkout@v2.3.2
+      -
         name: Prepare
-        id: prepare
+        id: prep
         run: |
           echo ::set-output name=build_tag::test
           echo ::set-output name=container_name::jetbrains-license-server
           echo ::set-output name=running_timeout::120
           echo ::set-output name=running_log_check::is listening on
       -
-        name: Checkout
-        uses: actions/checkout@v2.3.2
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
       -
         name: Set up Docker Buildx
-        uses: crazy-max/ghaction-docker-buildx@v3.3.0
+        uses: docker/setup-buildx-action@v1
       -
-        name: Docker Buildx
-        run: |
-          docker buildx build --load --tag ${{ steps.prepare.outputs.build_tag }} --file Dockerfile .
+        name: Build
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./Dockerfile
+          load: true
+          tags: ${{ steps.prep.outputs.build_tag }}
       -
         name: Start container
         run: |
-          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
-          docker run -d --name ${{ steps.prepare.outputs.container_name }} \
+          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
+          docker run -d --name ${{ steps.prep.outputs.container_name }} \
             -e "JLS_VIRTUAL_HOSTS=docker.test" \
-            ${{ steps.prepare.outputs.build_tag }}
+            ${{ steps.prep.outputs.build_tag }}
       -
         name: Test run
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
+          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
+            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
               echo "🎉 Container up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prepare.outputs.container_name }} container"
-              docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.container_name }} container"
+              docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
               exit 1
             fi
-          done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
+          done < <(docker logs -f ${{ steps.prep.outputs.container_name }} 2>&1)
 
-          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
+          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prep.outputs.container_name }})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
-            >&2 echo "❌ Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
-            docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+            >&2 echo "❌ Container ${{ steps.prep.outputs.container_name }} returned status '$CONTAINER_STATUS'"
+            docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
             exit 1
           fi
-          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
           echo
